### ISSUE TITLE
Your contributions to OpenRefine

### ISSUE THREAD

**Issue by wetneb** [wetneb/hello-elebitzero#1]
Hello @elebitzero,

I wanted to write to you for some time, but GitHub does not have a private message functionality, and I do not know how to reach out to you via other media, so there you go!

You have opened nearly 100 pull requests on OpenRefine. All of really high quality. This is huge. I am extremely grateful for your involvement in the project.

I just want to make sure I do everything in my power to make that last. So do let me know if there is anything holding you back, anything you wish we were doing differently.

Specifically, I am thinking about the following things:

- You are already play a maintainer role, in many respects (by tackling a lot of maintenance tasks, giving your opinion on pull requests, and so on). If you have any interest in reviewing pull requests (which you have already done a
  few times) or cutting out releases, you are very welcome to. I totally trust your judgment with the Merge button. But I am also happy to keep working on this - so no pressure.

- We have funding opportunities, and hiring you on those funded projects would be really great in my opinion. With knowledge of what you are interested in working on, we can also direct the funding applications to make your work fit in it. With most of our grant applications, we are only able to hire developers as contractors, and for fairly short-term contracts, but we are also looking into ways to create proper stable jobs around OpenRefine. If you have any interest in this, let us (@trnstlntk or me) know. That being said, I also understand that this might not fit in your personal situation, and I want to make sure you can also keep contributing in a volunteer capacity without being sidelined by the funded projects.

- The advisory committee of OpenRefine is the body which is responsible for the project within Code for Science and Society, our fiscal sponsor. You are also welcome to join this. This would be in a volunteer capacity.

- We can send you to events related to OpenRefine, and represent the project there. Open source conferences, Wikimedia-related events, events organized by other user communities: let us know. This year I attended Data Harvest (a European data journalism conference) and it felt like in 3 days of conference I gathered enough motivation to keep working on the project for 5 more years. Meeting OpenRefine enthusiasts in person just makes me very happy.

- We also participate in internship programmes (Outreachy, Google Summer of Code) and are always looking for people to mentor interns in those programmes. If that is something you would be interested in, I am sure you would make a great mentor.

Again, if you can think of any other way you would want to contribute, let me know.

And perhaps things are just fine like they are, and that is totally fine - I really would not want to push you to a task you do not enjoy. I only want to propose those things just to make it clear that they are possible.

Keep up the amazing work, and all the best!

Antonin

**Comment by elebitzero** [comment]
@wetneb

Thank you for the kind words.

I have enjoyed contributing to OpenRefine in my spare time, and I appreciate the work you do to actively maintain the repository and encourage all of the contributors.

At this time, I don't have any more bandwidth to contribute to OpenRefine beyond what I am currently doing, as I am actively looking for a full-time software engineering job where I live (SF Bay Area).  You can keep me in mind for UI development for a funded project; If the fit and timing is good, I am open to that.

OpenRefine is a worthy project to contribute to.  If I had unlimited time, I'd rewrite the UI in React/Bootstrap/TypeScript.

**Comment by trnstlntk** [comment]
Thanks for your response, @elebitzero, and good luck on the job hunt. If a reference from us at OpenRefine would help, we'd be happy to provide it.

We will certainly keep you in mind for paid UI-focused work in the future.

And of course thanks for all you do, and keep doing. Never hesitate to let us know if we can help you somewhere.
